User.create(username: 'test1', password: 'password')
User.create(username: 'test2', password: 'password')
User.create(username: 'test3', password: 'password')
User.create(username: 'test4', password: 'password')
User.create(username: 'test5', password: 'password')